# Generated by Django 3.2.5 on 2021-07-19 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobile',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='electronics/mobiles'),
        ),
    ]
